<ButtonScreenView>

    MDCarousel:
        id: carousel
        on_index: root.on_index(args[1])
        on_slide_progress: root.do_animation_slide_content(*args)

        ButtonScreenOneScreen:
        ButtonScreenTwoScreen:


    Dots:
        id: dots
        y: "24dp"

    MDIconButton:
        icon: "arrow-left"
        md_bg_color: 0, 0, 0, .2
        x: "12dp"
        pos_hint: {"top": .98}
        on_release: app.manager_screen.current = "menu"
